In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
len(df[df.Category == "ham"]) # ham = not spam 

4825

In [4]:
len(df[df.Category == "spam"])

747

In [5]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
4516+641

5157

In [8]:
df["spam"] = df["Category"].replace(to_replace=["ham", "spam"], value=[0,1])

In [9]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [10]:
spams = df["Message"][df["Category"] == "spam"][:5]
for i in spams : 
    print("Message: ")
    print(i)
    print()

Message: 
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

Message: 
FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv

Message: 
WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.

Message: 
Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030

Message: 
SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info



In [11]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam, train_size=.8)

In [13]:
y_train

3963    1
1539    0
1917    0
1230    0
2282    0
       ..
67      1
2747    0
777     0
1616    0
3386    0
Name: spam, Length: 4457, dtype: int64

In [14]:
X_train 

3963    You have been specially selected to receive a ...
1539                             Midnight at the earliest
1917    Fffff. Can you text kadeem or are you too far ...
1230                      Jus ans me lar. U'll noe later.
2282    I hav almost reached. Call, i m unable to conn...
                              ...                        
67      Urgent UR awarded a complimentary trip to Euro...
2747                        K da:)how many page you want?
777     Why don't you go tell your friend you're not s...
1616                         Mm i had my food da from out
3386                                            Ok can...
Name: Message, Length: 4457, dtype: object

In [15]:
X_test

2308    WIN a year supply of CDs 4 a store of ur choic...
4256    Block Breaker now comes in deluxe format with ...
2381    If i let you do this, i want you in the house ...
2879    Hey Boys. Want hot XXX pics sent direct 2 ur p...
2916    Nothing lor... A bit bored too... Then y dun u...
                              ...                        
543     But am going to college pa. What to do. are el...
2175                        See? I thought it all through
2909    Why must we sit around and wait for summer day...
2559    Some friends want me to drive em someplace, pr...
569     Love it! Daddy will make you scream with pleas...
Name: Message, Length: 1115, dtype: object

In [16]:
y_train

3963    1
1539    0
1917    0
1230    0
2282    0
       ..
67      1
2747    0
777     0
1616    0
3386    0
Name: spam, Length: 4457, dtype: int64

In [17]:
len(X_train[:1].to_list()[0].split())

23

In [18]:
type(X_train) 

pandas.core.series.Series

In [19]:
type(X_train.values)

numpy.ndarray

Ahmed Eats Food <br>
Moahmed Eats Fruit  <br> 

Ahmed Eats Food Fruit Mohamed

  1    1    1     0     0  <br>
  0    1    0     1     1  <br> 

In [ ]:
represent each row as a vector of numbers 

vector size = number of unique words 

hello, my name is ahmed, welcome to egypt, it  a  great city to travel 
0      0    0  0    0       0    0   0     0   0   0      0    0    0
1      0    0  0    0       0    0   1     0   0   0      0    0    0 
0      1    1  1    1       0    0   0     0   0   0      0    0    0
1      0    0  0    0       1    1   1     0   0   0      0    0    0 
0      0    0  1    0       1    1   2     0   1   1      1    1    1    
0      1    0  1    0       0    0   0     0   0   1      1    0    0

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[0].shape

(7730,)

In [21]:
X_train_count

<4457x7730 sparse matrix of type '<class 'numpy.int64'>'
	with 59184 stored elements in Compressed Sparse Row format>

In [22]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [23]:
emails = [
    'Hey Mohamed, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [24]:
print(model.predict_proba(emails_count)) 

[[9.99950834e-01 4.91659450e-05]
 [1.23921437e-02 9.87607856e-01]]


In [26]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9811659192825112

**Sklearn Pipeline**

In [27]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [28]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [29]:
clf.score(X_test,y_test)

0.9811659192825112

In [30]:
clf.predict(emails)

array([0, 1])